import { useEffect, useState } from "react";

export default function Disclaimer() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    try {
      const token = localStorage.getItem("taa_token");
      setIsLoggedIn(!!token);
    } catch {
      setIsLoggedIn(false);
    }
  }, []);

  const backHref = isLoggedIn ? "/dashboard" : "/";

  return (
    <div
      className="legal-page"
      style={{
        padding: "3rem 1.5rem",
        maxWidth: "900px",
        margin: "0 auto",
      }}
    >
      {/* Tiny back pill */}
      <div style={{ marginBottom: "1rem" }}>
        <a
          href={backHref}
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "0.35rem",
            padding: "0.35rem 0.75rem",
            borderRadius: "999px",
            border: "1px solid rgba(148,163,184,0.5)",
            fontSize: "0.8rem",
            color: "#e5e7eb",
            textDecoration: "none",
            background: "rgba(15,23,42,0.9)",
          }}
        >
          <span style={{ fontSize: "0.95rem" }}>←</span>
          <span>
            Back to {isLoggedIn ? "dashboard" : "home"}
          </span>
        </a>
      </div>

      {/* Header */}
      <header
        style={{
          marginBottom: "2rem",
          borderBottom: "1px solid rgba(148,163,184,0.4)",
          paddingBottom: "1.5rem",
        }}
      >
        <p
          style={{
            fontSize: "0.75rem",
            letterSpacing: "0.16em",
            textTransform: "uppercase",
            color: "#a1a1aa",
            marginBottom: "0.4rem",
          }}
        >
          Quantum Innovation Systems LLC
        </p>
        <h1 style={{ fontSize: "2rem", marginBottom: "0.4rem" }}>
          Risk Disclaimer
        </h1>
        <p style={{ fontSize: "0.9rem", color: "#9ca3af" }}>
          Applies to use of the TradingAI Analyzer™ software and related
          services.
        </p>
        <p
          style={{
            marginTop: "0.75rem",
            fontSize: "0.8rem",
            color: "#6b7280",
          }}
        >
          Last updated: January 2025
        </p>
      </header>

      <div
        style={{
          borderRadius: "1rem",
          border: "1px solid rgba(148,163,184,0.35)",
          padding: "1.75rem 1.6rem",
          background:
            "radial-gradient(circle at top, rgba(56,189,248,0.06), transparent 55%) #020617",
        }}
      >
        <section style={{ marginBottom: "1.5rem" }}>
          <h2 style={{ fontSize: "1.15rem", marginBottom: "0.5rem" }}>
            Educational Purposes Only
          </h2>
          <p style={{ fontSize: "0.95rem", color: "#e5e7eb" }}>
            TradingAI Analyzer™ is a software product owned and operated by{" "}
            <strong>Quantum Innovation Systems LLC</strong> (“we”, “our”,
            “us”). The Platform provides automated chart analysis for{" "}
            <strong>educational and informational purposes only</strong>. It is
            designed to help you structure ideas and journal your thinking, not
            to tell you what to trade.
          </p>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h2 style={{ fontSize: "1.15rem", marginBottom: "0.5rem" }}>
            No Financial Advice
          </h2>
          <p style={{ fontSize: "0.95rem", color: "#e5e7eb" }}>
            Nothing generated by this Platform—including plans, summaries,
            alerts, or any other output—constitutes investment advice, a
            recommendation, or an instruction to buy or sell any security,
            derivative, or financial product. You should consult an independent
            financial advisor if you need personalized advice.
          </p>
        </section>

        <section style={{ marginBottom: "1.5rem" }}>
          <h2 style={{ fontSize: "1.15rem", marginBottom: "0.5rem" }}>
            Risk of Trading
          </h2>
          <p style={{ fontSize: "0.95rem", color: "#e5e7eb" }}>
            Trading and investing in financial markets involve{" "}
            <strong>significant risk</strong>. You can lose some, all, or more
            than your initial capital. Past performance—whether real,
            hypothetical, or simulated—does not guarantee future results. You
            are solely responsible for any trades you place and the outcomes of
            those trades.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: "1.15rem", marginBottom: "0.5rem" }}>
            Limitation of Liability
          </h2>
          <p style={{ fontSize: "0.95rem", color: "#e5e7eb" }}>
            Quantum Innovation Systems LLC, its owners, operators, employees,
            and developers will not be liable for any direct, indirect,
            incidental, consequential, or special damages arising out of or in
            any way connected with your use of TradingAI Analyzer™. By using
            the Platform, you agree that{" "}
            <strong>all trading decisions are your own</strong>.
          </p>
        </section>
      </div>
    </div>
  );
}
