export default function FAQ() {
  return (
    <section id="faq" className="section">
      <div className="section-inner">
        <h2 className="section-title">Frequently asked questions</h2>
        <p className="section-sub">
          If it’s not answered here, reach out and ask.
        </p>

        <div className="faq-list">
          <div className="faq-item">
            <h3>Is this financial advice?</h3>
            <p>
              No. TradingAI Analyzer is an educational and informational tool.
              Nothing generated by the platform is a recommendation to buy or
              sell any asset.
            </p>
          </div>

          <div className="faq-item">
            <h3>What markets does it work on?</h3>
            <p>
              Any market you can screenshot—futures, stocks, forex, crypto—as
              long as the candles and price axis are visible.
            </p>
          </div>

          <div className="faq-item">
            <h3>How fast do I get a plan?</h3>
            <p>
              Most screenshots return a full plan in a few seconds. During heavy
              load, it may take slightly longer.
            </p>
          </div>

          <div className="faq-item">
            <h3>Can I cancel anytime?</h3>
            <p>
              Yes. You can cancel from your account area. You’ll keep access
              until the end of your billing period.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
